language: node_js
os:
  - linux
dist: xenial
branches:
  only:
    - main
node_js:
  - 'node'
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database armory_test;' -U postgres
