name: PostgreSQL Service Example
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: armory-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
          
      - name: Test
        run: yarn test
        env:
          PORT: 5000
          CORS_ORIGIN: http://localhost:3000
          JWT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMjM1Nzg1MSwiaWF0IjoxNjMyMzU3ODUxfQ.Pp9VYlhVAYA7IGxj2QM8dlBvT7ccgM8m8p31Rk82wm0
          DB_NAME: armory-test
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          LOG_DIR: ./
          INITIAL_USER: test@email.com
          INITIAL_PASSWORD: password
